### ISSUE TITLE
Extension throws exception

### ISSUE THREAD

**Issue by rhnkyr** [weisJ/auto-dark-mode#80] opened 2024-02-05 05:58 UTC
Hi, thanks for this extension. 

My M1 MAC throws this issue below. 

`java.lang.Throwable: Daemon listeners already initialized for the project ProjectDefault (Template) Project
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)` and other dump lines. 

The PHPStrom version is 2023.3.3

**Comment by weisJ** [comment] 2024-02-05 09:11
Could you provide more of the log? At first glance this doesn’t look like something caused by auto dark mode.

**Comment by weisJ** [comment] 2024-03-16 11:56
Closing this due to missing information.

**Closed by weisJ** 2024-03-16 11:56 UTC
